Repository carflor/ArtisTry, pull requests merged in 2020-07, with the labels that each got.

#4 Feature/components
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Gallery/Gallery.test.js
  src/Painting/Painting.css
  src/Painting/Painting.js
  src/Painting/Painting.test.js
  src/apiCalls.js
  src/index.js
Labels: enhancement

#8 Unit testing for painting component
  package-lock.json
  package.json
  src/Painting/Painting.test.js
  src/index.js
Labels: enhancement

#11 Feature/setup router
  pull_request-template.md
  src/App/App.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Painting/Painting.css
  src/Painting/Painting.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/PaintingInfo/PaintingInfo.test.js
  src/apiCalls.js
Labels: enhancement

#21 Feature/hooks
  package-lock.json
  package.json
  src/App/App.js
  src/Hooks/usePaintings.js
  yarn.lock
Labels: enhancement

#27 Feature/painter page
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Gallery/Gallery.css
  src/Hooks/usePaintings.js
  src/PainterInfo/PainterInfo.css
  src/PainterInfo/PainterInfo.js
  src/PainterInfo/PainterInfo.test.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/PaintingInfo/PaintingInfo.test.js
  src/assets/back-btn.png
  src/assets/offwhite wall.jpeg
  src/assets/offwhite wallpaper.jpg
  src/assets/tagIcon.png
  src/assets/wall1.jpeg
  src/assets/wall2.jpeg
  src/assets/wall3.jpeg
  src/index.css
Labels: enhancement

#28 Feature/artist gallery
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Hooks/useArtistInfo.js
  src/Hooks/usePaintingInfo.js
  src/Hooks/usePaintings.js
  src/Hooks/usePaintings.test.js
  src/PainterInfo/PainterInfo.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
Labels: enhancement

#33 Feature/painter works
  src/App/App.css
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/PainterInfo/PainterInfo.js
  src/Painting/Painting.css
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/PaintingInfo/PaintingInfo.test.js
Labels: enhancement

#36 Feature/random art
  src/App/App.css
  src/App/App.js
  src/Gallery/Gallery.js
  src/RandomArt/RandomArt.css
  src/RandomArt/RandomArt.js
  src/RandomArt/randomTerms.js
Labels: enhancement

#42 Styling/background
  src/App/App.css
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
Labels: enhancement

#48 Feature/painting display
  src/App/App.css
  src/App/App.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Gallery/Gallery.test.js
  src/Hooks/usePaintings.test.js
  src/PainterInfo/PainterInfo.css
  src/PainterInfo/PainterInfo.js
  src/PainterInfo/PainterInfo.test.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/RandomArt/RandomArt.css
  src/RandomArt/RandomArt.js
  src/RandomArt/randomTerms.js
Labels: bug, enhancement

#54 Hook refactor
  src/App/App.css
  src/App/App.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Hooks/usePaintingSummary.js
  src/Hooks/usePaintingSummary.test.js
  src/Hooks/usePaintings.js
  src/PainterInfo/PainterInfo.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/PaintingInfo/PaintingInfo.test.js
  src/RandomArt/RandomArt.js
Labels: enhancement

#61 Bug/randomart
  src/App/App.css
  src/App/App.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Hooks/usePaintings.js
  src/Hooks/usePaintings.test.js
  src/PainterInfo/PainterInfo.js
  src/Painting/Painting.css
  src/Painting/Painting.js
  src/PaintingInfo/PaintingInfo.js
  src/RandomArt/RandomArt.js
  src/RandomArt/randomTerms.js
Labels: bug

#63 Feature/prop types
  src/App/App.css
  src/App/App.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/PainterInfo/PainterInfo.js
  src/Painting/Painting.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/RandomArt/RandomArt.js
  src/UserGallery/UserGallery.css
  src/UserGallery/UserGallery.js
Labels: enhancement

#64 Feature/painter info bugfix
  src/App/App.js
  src/App/App.test.js
  src/PainterInfo/PainterInfo.js
  src/PaintingInfo/PaintingInfo.css
  src/UserGallery/UserGallery.test.js
  src/assets/selectedTag.png
  src/assets/unselectedTag.png
Labels: bug

#65 Testing/components
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Gallery/Gallery.js
  src/Hooks/usePaintings.js
  src/PainterInfo/PainterInfo.js
  src/Painting/Painting.js
  src/RandomArt/RandomArt.js
  src/RandomArt/RandomArt.test.js
Labels: bug, enhancement

#70 Missing data favs bug
  src/PainterInfo/PainterInfo.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/RandomArt/randomTerms.js
Labels: bug

#72 Feature/linter
  package-lock.json
  package.json
  src/.eslintrc
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/ArtistGallery/ArtistGallery.js
  src/ArtistGallery/ArtistGallery.test.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Gallery/Gallery.test.js
  src/Hooks/useArtistInfo.js
  src/Hooks/usePaintingInfo.js
  src/Hooks/usePaintingInfo.test.js
  src/Hooks/usePaintingSummary.js
  src/Hooks/usePaintingSummary.test.js
  src/Hooks/usePaintings.js
  src/Hooks/usePaintings.test.js
  src/PainterInfo/PainterInfo.js
  src/PainterInfo/PainterInfo.test.js
  src/Painting/Painting.js
  src/Painting/Painting.test.js
  src/PaintingInfo/PaintingInfo.css
  src/PaintingInfo/PaintingInfo.js
  src/PaintingInfo/PaintingInfo.test.js
  src/RandomArt/RandomArt.js
  src/RandomArt/RandomArt.test.js
  src/RandomArt/randomTerms.js
  src/UserGallery/UserGallery.js
  src/UserGallery/UserGallery.test.js
Labels: enhancement
